name: learn-github-actions
on: [push]
jobs:
  my-testing:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python.version: 3.7
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run flake8
      run: | 
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run test
      run: python -m pytest —import-mode=append tests/
      
